name: Build Aseprite (Linux x64)
on:
  workflow_dispatch:
    inputs:
      aseprite-tag:
        required: true
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Get Repo
      run: git clone https://github.com/aseprite/aseprite --recursive -b ${{ github.event.inputs.aseprite-tag }}

    - name: Get Skia Pre-Built
      run: |
        sudo rm -rf $HOME/deps/skia/
        curl -L https://github.com/aseprite/skia/releases/download/m102-861e4743af/Skia-Linux-Release-x64-libstdc++.zip -o skia.zip
        mkdir -p $HOME/deps/skia
        unzip skia.zip -d $HOME/deps/skia

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: ubuntu-latest-on

    - uses: seanmiddleditch/gha-setup-ninja@master

    - name: Install Dependencies
      shell: bash
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y g++ clang libc++-dev libc++abi-dev cmake ninja-build libx11-dev libxcursor-dev libxi-dev libgl1-mesa-dev libfontconfig1-dev

    - name: Generating Makefiles
      shell: bash
      run: |
        export enable_ccache=on
        export CC=clang
        export CXX=clang++
        cd aseprite/
        cmake -S . -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_CXX_FLAGS:STRING=-stdlib=libstdc++ \
          -DCMAKE_EXE_LINKER_FLAGS:STRING=-stdlib=libstdc++ \
          -DLAF_BACKEND=skia \
          -DSKIA_DIR=$HOME/deps/skia \
          -DSKIA_LIBRARY_DIR=$HOME/deps/skia/out/Release-x64 \
          -DSKIA_LIBRARY=$HOME/deps/skia/out/Release-x64/libskia.a \
          -DENABLE_CCACHE=$enable_ccache

    - name: Compiling
      shell: bash
      run: |
        cd aseprite/
        cmake --build build/ --parallel 3 --config Release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: aseprite-linux-x64
        path: ./aseprite/build/bin
        if-no-files-found: error
