name: Build Aseprite (Windows x64)
on:
  workflow_dispatch:
    inputs:
      aseprite-tag:
        required: true
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Get Repo
      run: |
        curl -L https://github.com/aseprite/aseprite/releases/download/${{ github.event.inputs.aseprite-tag }}/Aseprite-${{ github.event.inputs.aseprite-tag }}-Source.zip --output ase.zip
        7z x ase.zip -o.\

    - name: Get Skia Pre-Built
      run: |
        curl -L https://github.com/aseprite/skia/releases/download/m102-861e4743af/Skia-Windows-Release-x64.zip -o skia.zip
        mkdir -p .\skia
        7z x skia.zip -o.\skia\

    - uses: hendrikmuhs/ccache-action@v1

    - name: Workaround for windows-2022 and cmake 3.25.0
      shell: bash
      run: rm -rf C:/Strawberry/

    - uses: ilammy/msvc-dev-cmd@v1

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1

    - name: Generating Build Files
      shell: bash
      run: |
        export enable_ccache=off
        cmake -S . -B build -G "Visual Studio 17 2022" \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 \
          -DENABLE_TESTS=OFF \
          -DENABLE_TESTS=OFF \
          -DLAF_BACKEND=skia \
          -DSKIA_DIR=./skia \
          -DSKIA_LIBRARY_DIR=./skia/out/Release-x64 \
          -DSKIA_LIBRARY=./skia/out/Release-x64/skia.lib \
          -DENABLE_CCACHE=$enable_ccache

    - name: Compile
      shell: bash
      run: |
        cmake --build build/ --parallel 3 --config Release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: aseprite-windows-x64
        path: ./build/bin
        if-no-files-found: error
